version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  deploy-to-s3:
    jobs:
      - build
      - test:
          requires:
            - build
      - release_feat:
          context: aws
          filters:
            branches:
              only: /^feat-.*/
          requires:
            - test
      - release_main:
          context: aws
          filters:
            branches:
              only:
                - main
          requires:
            - test

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'Building now...'
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'Testing now...'
  release_feat:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: echo 'Deploying (feat) now...'
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://demo.mayoct.net/${CIRCLE_USERNAME}'
  release_main:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: echo 'Deploying (main) now...'
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://demo.mayoct.net'
